### ISSUE TITLE
Update to support new metrics endpoint in mesos 0.22.0

### ISSUE THREAD

**Issue by mindscratch** [rayrod2030/collectd-mesos#10]
With mesos 0.22.0 the metrics enpoint is no longer `/metrics.json`, it's now `/metrics/snapshot`. See https://youtu.be/LC3dlmdc4bc?t=967.

**Comment by rayrod2030** [comment]
I'm pretty sure we have been using the metrics/snapshot since 0.19.0 in anticipation of stats.json getting deprecated.  Stats.json is mentioned in the repository description so I have updated that.  Thanks for the heads up!
