### ISSUE TITLE
Many collectd log entries when using mesos-master.py on an elected master node

### ISSUE THREAD

**Issue by mre** [rayrod2030/collectd-mesos#16]
I get many log entries in /var/log/collectd.log when running collectd-mesos on a master node that is elected as a leader:
    [2015-09-01 11:15:12] [warning] mesos-master plugin: Value not found for master/task_lost/source_master/reason_slave_removed

The result is, that the log is continuously growing, even though there's nothing wrong.
Maybe this message could be removed or optionally disabled somehow?

Here's my config:

    <Plugin "python">
        ModulePath "/usr/share/collectd/plugins/"
        Import "mesos-master"
        <Module "mesos-master">
            Instance "test"
            Host "127.0.0.1"
            Port 5050
            Verbose false
            Version "0.22.1"
        </Module>
    </Plugin>

**Comment by mre** [comment]
curl http://127.0.0.1:5050/metrics/snapshot

    {
    "master/cpus_percent": 0.00625,
    "master/cpus_total": 32,
    "master/cpus_used": 0.2,
    "master/disk_percent": 0.000564174894217207,
    "master/disk_total": 85080,
    "master/disk_used": 48,
    "master/dropped_messages": 2,
    "master/elected": 1,
    "master/event_queue_dispatches": 6,
    "master/event_queue_http_requests": 0,
    "master/event_queue_messages": 0,
    "master/frameworks_active": 2,
    "master/frameworks_connected": 2,
    "master/frameworks_disconnected": 0,
    "master/frameworks_inactive": 0,
    "master/invalid_framework_to_executor_messages": 0,
    "master/invalid_status_update_acknowledgements": 0,
    "master/invalid_status_updates": 0,
    "master/mem_percent": 0.00135095199898679,
    "master/mem_total": 94748,
    "master/mem_used": 128,
    "master/messages_authenticate": 0,
    "master/messages_deactivate_framework": 0,
    "master/messages_decline_offers": 4750840,
    "master/messages_exited_executor": 0,
    "master/messages_framework_to_executor": 0,
    "master/messages_kill_task": 0,
    "master/messages_launch_tasks": 56917,
    "master/messages_reconcile_tasks": 35417,
    "master/messages_register_framework": 0,
    "master/messages_register_slave": 2,
    "master/messages_reregister_framework": 9,
    "master/messages_reregister_slave": 12,
    "master/messages_resource_request": 0,
    "master/messages_revive_offers": 0,
    "master/messages_status_update": 293405,
    "master/messages_status_update_acknowledgement": 293405,
    "master/messages_unregister_framework": 0,
    "master/messages_unregister_slave": 0,
    "master/outstanding_offers": 0,
    "master/recovery_slave_removals": 0,
    "master/slave_registrations": 2,
    "master/slave_removals": 2,
    "master/slave_reregistrations": 2,
    "master/slave_shutdowns_canceled": 0,
    "master/slave_shutdowns_scheduled": 2,
    "master/slaves_active": 2,
    "master/slaves_connected": 2,
    "master/slaves_disconnected": 0,
    "master/slaves_inactive": 0,
    "master/task_failed/source_slave/reason_command_executor_failed": 34,
    "master/tasks_error": 0,
    "master/tasks_failed": 625,
    "master/tasks_finished": 143040,
    "master/tasks_killed": 0,
    "master/tasks_lost": 0,
    "master/tasks_running": 2,
    "master/tasks_staging": 0,
    "master/tasks_starting": 0,
    "master/uptime_secs": 7794860.4021609,
    "master/valid_framework_to_executor_messages": 0,
    "master/valid_status_update_acknowledgements": 293405,
    "master/valid_status_updates": 293405,
    "registrar/queued_operations": 0,
    "registrar/registry_size_bytes": 419,
    "registrar/state_fetch_ms": 16.600064,
    "registrar/state_store_ms": 11.29216,
    "registrar/state_store_ms/count": 2,
    "registrar/state_store_ms/max": 11.29216,
    "registrar/state_store_ms/min": 10.879232,
    "registrar/state_store_ms/p50": 11.085696,
    "registrar/state_store_ms/p90": 11.2508672,
    "registrar/state_store_ms/p95": 11.2715136,
    "registrar/state_store_ms/p99": 11.28803072,
    "registrar/state_store_ms/p999": 11.291747072,
    "registrar/state_store_ms/p9999": 11.2921187072,
    "system/cpus_total": 16,
    "system/load_15min": 0.11,
    "system/load_1min": 0.16,
    "system/load_5min": 0.1,
    "system/mem_free_bytes": 47159783424,
    "system/mem_total_bytes": 50749054976
    }

**Comment by IngaFeick** [comment]
+1

**Comment by rayrod2030** [comment]
@mre @IngaFeick  If you set your collectd syslog plugin LogLevel to "err" you should not see these warnings in your log file.  The other option is to make these warnings only appear when Verbose Logging is enabled.   Thoughts?

**Comment by mre** [comment]
Maybe it makes sense to go with the second option. Warnings are usually quite important on collectd. They point out that something might be wrongly configured. The behavior here is expected, it seems. It is more of an info text to me and it's occurring pretty often which makes the log grow fast. To be honest I thought it was a bug, because it did not go away when I set Verbose to false.
So yeah, from my side only show in verbose mode. :+1:

**Comment by rayrod2030** [comment]
Addressed in https://github.com/rayrod2030/collectd-mesos/commit/8f71161cd51547fe8f712f12ac3f288ab8fee716

**Comment by mre** [comment]
Perfect. Thank you!
