### ISSUE TITLE
slave monitoring?

### ISSUE THREAD

**Issue by rasputnik** [rayrod2030/collectd-mesos#4]
Notice the slaves have similar stats exposed, would be good to see that too.

**Comment by rayrod2030** [comment]
I'll work on this today.  Thanks for the heads up!

**Comment by rasputnik** [comment]
I threw something together here (shamelessly 'inspired' by your mesos-master version):

    https://gist.github.com/rasputnik/b749c39f691edc9b8ecd

**Comment by rayrod2030** [comment]
This is great thank you @rasputnik.  Based on your code I guess it makes sense to split this plugin off into a mesos-master and mesos-slave files.  What do you think?

**Comment by rasputnik** [comment]
Heh, I only did it that way because I couldn't see an easy way to support both in the same plugin :)

Having said that, most production setups wouldn't be co-hosting the master and slave process so I'd guess most people would deploy only one of these per-node - so yes, I think splitting them out makes sense.

**Comment by rayrod2030** [comment]
@rasputnik Slave monitoring now merged to master.  Thanks!
