### ISSUE TITLE
are all these metrics actually gauges?

### ISSUE THREAD

**Issue by rasputnik** [rayrod2030/collectd-mesos#8]
Looking at the master stats for example, it seems like at least these are counters,
not gauges:

* master/invalid_status_updates
* master/messages_kill_task
* master/messages_launch_tasks
* master/messages_reconcile_tasks
* master/messages_register_framework
* master/messages_register_slave
* master/messages_reregister_framework
* master/messages_reregister_slave
* master/messages_status_update
* master/messages_status_update_acknowledgement
* master/recovery_slave_removals
* master/slave_registrations
* master/slave_removals
* master/slave_reregistrations

and i've probably missed a few :)

**Comment by rayrod2030** [comment]
Could very well be.  I'll review them today.  Thanks!

**Comment by rayrod2030** [comment]
@rasputnik I went through all of the metrics and changed them to reflect their correct metric type based on the mesos source code.  Thanks for the heads up!

**Comment by rasputnik** [comment]
No worries, thanks for sorting it :)
